### ISSUE TITLE
Unable to fetch connectors

### ISSUE THREAD

**Issue by quanyshh** [matth-x/ArduinoOcppSimulator#5]
![изображение](https://github.com/matth-x/ArduinoOcppSimulator/assets/29192087/12c367b3-61de-421e-96fe-fc4a73c428fe)
Hello, an error comes out "Unable to fetch connectors". Are there any instructions on the simulator

**Comment by agruenb** [comment]
This means most probably that the request timed out. Are you sure that the simulator is still running? Try visiting `http://localhost:8000/api/connectors` in your browser while the simulator is running. If the api is reachable it should display something like: `["1","2"]`

**Comment by aviarybuilds** [comment]
the website forces all api calls to localhost. Is there a way to use the computer's IP address instead? i'm trying to run this in a headless VM, and would love to be able to access the web portal through the intranet connection instead of using the browser on the desktop of the PC itself

![Uploading image.png…]()

**Comment by matth-x** [comment]
@aviarybuilds The relevant spot in the sources is the nodejs environment manifest (e.g. [.env.development](https://github.com/agruenb/micro-ocpp-dashboard/blob/master/.env.development)). A short documentation of the API root definition is in the [API configuration](https://github.com/agruenb/micro-ocpp-dashboard/tree/master#api-configuration) section.

As a general background, the Simulator comes with a compiled version of the dashboard. If you want to change the dashboard (e.g. the API root), then you need to edit the dashboard sources and rebuild it, so that the Simulator can use the new compiled version. A brief overview of the build process is given in [this section](https://github.com/matth-x/MicroOcppSimulator#building-the-webapp-developers) of the README. Furthermore, the whole README of the [dashboard](https://github.com/agruenb/micro-ocpp-dashboard) repo is very relevant.

If you encounter any problems, please update this issue with your findings. I only tested the Simulator on the local host so far, but would be very interested in arbitrary base URLs support.

**Comment by eiwin** [comment]
I had the same issue with a headless VM. Then I did this and it works for me.
Copy .env.development to .env.production, and then change localhost to your ip adress. Copied the compiled and compressed file according to the description. Then I can access the webpage using ip adress.
Thanks @matth-x for the beautiful work.

> the website forces all api calls to localhost. Is there a way to use the computer's IP address instead? i'm trying to run this in a headless VM, and would love to be able to access the web portal through the intranet connection instead of using the browser on the desktop of the PC itself ![simulator](https://private-user-images.githubusercontent.com/154609542/292506770-a95f2b5c-1c10-42cc-898c-f302c255812e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ1MDY0MTUsIm5iZiI6MTcwNDUwNjExNSwicGF0aCI6Ii8xNTQ2MDk1NDIvMjkyNTA2NzcwLWE5NWYyYjVjLTFjMTAtNDJjYy04OThjLWYzMDJjMjU1ODEyZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwNlQwMTU1MTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MTIwYjI5MDFjZTAxMjY4Nzc3MjFkNWIyNjc5MzIzYmQ5NjEwOTgwMWUzYjQxMTM3ZDgwZGViM2Q5YzdhMmRhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.pn4eOVOtNy5st7tX1hy9oDgrtBpoLkiwWS8SYRAlTzI)

**Comment by GanesanGuru** [comment]
Hi @matth-x @eiwin ,
I've tried the same by editing the .env.production file, yet unable to compile. I'm getting error @ npm build part. The log is attached as follows. Kindly do let me know, what am I missing!!
[ocpp_log.txt](https://github.com/matth-x/MicroOcppSimulator/files/13973279/ocpp_log.txt)

**Comment by Gazdella** [comment]
Hello @matth-x , I edited .env.development file with my ip but I cant find .env.production .
I still got same issue "Unable to fetch connectors".
Could you please help me?

**Comment by agruenb** [comment]
> Hello @matth-x , I edited .env.development file with my ip but I cant find .env.production . I still got same issue "Unable to fetch connectors". Could you please help me?

There is no _.env.production_ file in the repository. You have to manually create it and then copy the contents of the _.env.development_ file into it. After that you can alter the variables to your liking and build the bundle.

**Comment by Gazdella** [comment]
I created it but still got same error <img width="1205" alt="Screenshot 2024-06-14 at 3 35 20 PM" src="https://github.com/matth-x/MicroOcppSimulator/assets/167681349/b51fc059-18aa-43c5-b476-8c35e468bb22">

**Comment by agruenb** [comment]
Could you please add some more information about the error? Have you opened the browser network tool and checked that the correct address is used? Did you rebuild the webapp manually or did you use the script?

**Comment by Gazdella** [comment]
It still shows localhost in network tool, here is an error I get once I try to rebuild
<img width="878" alt="Screenshot 2024-06-14 at 4 10 14 PM" src="https://github.com/matth-x/MicroOcppSimulator/assets/167681349/5f93dfb9-5afd-4101-90c7-8688be8ab515">

**Comment by Gazdella** [comment]
It still shows localhost in network tool, here is an error I get once I try to rebuild
<img width="1054" alt="Screenshot 2024-06-14 at 4 39 53 PM" src="https://github.com/matth-x/MicroOcppSimulator/assets/167681349/8573247e-9792-439e-888a-45572e7c721b">

**Comment by novta** [comment]
I have faced the same problem.
After the 
`cp .env.development .env.production`
in main folder level (MicroOcppSimulator folder) run
`sudo bash ./build-webapp/build_webapp.sh`
The result is 
`:~/MicroOcppSimulator$ sudo bash ./build-webapp/build_webapp.sh 
[info] NodeJS and npm need to be installed to build the web-app
Building web-app...
production environment found
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@jest/schemas@29.6.3',
npm WARN EBADENGINE   required: { node: '^14.15.0 || ^16.10.0 || >=18.0.0' },
npm WARN EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@jest/types@29.6.3',
npm WARN EBADENGINE   required: { node: '^14.15.0 || ^16.10.0 || >=18.0.0' },
npm WARN EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@svgr/babel-plugin-remove-jsx-attribute@8.0.0',
npm WARN EBADENGINE   required: { node: '>=14' },
npm WARN EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@svgr/babel-plugin-remove-jsx-empty-expression@8.0.0',
npm WARN EBADENGINE   required: { node: '>=14' },
npm WARN EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'css-minimizer-webpack-plugin@4.2.2',
npm WARN EBADENGINE   required: { node: '>= 14.15.0' },
npm WARN EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'jest-util@29.6.3',
npm WARN EBADENGINE   required: { node: '^14.15.0 || ^16.10.0 || >=18.0.0' },
npm WARN EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'jest-worker@29.6.4',
npm WARN EBADENGINE   required: { node: '^14.15.0 || ^16.10.0 || >=18.0.0' },
npm WARN EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }
npm WARN EBADENGINE }

up to date, audited 646 packages in 2s
 
86 packages are looking for funding
  run `npm fund` for details
 
17 vulnerabilities (3 low, 5 moderate, 8 high, 1 critical)
 
To address all issues, run:
  npm audit fix
 
Run `npm audit` for details.
 
> build
> webpack --config webpack_config/webpack.prod.js
 
[webpack-cli] Failed to load '/home/azadmin/MicroOcppSimulator/webapp-src/webpack_config/webpack.prod.js' config
[webpack-cli] /home/azadmin/MicroOcppSimulator/webapp-src/node_modules/jest-worker/build/index.js:126
      enableWorkerThreads: this._options.enableWorkerThreads ?? false,


SyntaxError: Unexpected token '?'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:85:18)
    at Object.<anonymous> (/home/azadmin/MicroOcppSimulator/webapp-src/node_modules/css-minimizer-webpack-plugin/dist/index.js:17:5)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)

:~/MicroOcppSimulator$`
